import type { Metadata } from "next";
import { Passions_Conflict, Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/ui/navigation/Navbar";
import Header from "@/ui/layout/Header";



const passions_Conflict = Passions_Conflict({
  variable: "--font-passions-sans",
  subsets: ["latin"],
  weight: "400"
});

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"]
});




export const metadata: Metadata = {
  title: "Cafe 64",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${passions_Conflict.variable} antialiased`}
      >
    <Header/>
        {/* <Navbar /> */}
        <main className="mx-10 mt-10 mb-30">

          {children}
        </main>

      </body>
    </html>
  );
}
